# Generated by scripts/generate-errors.js; do not edit.
MESSAGES = {
    "DOCKER_REQUIRED": "Docker with the Compose plugin is required. See README.md for macOS and Ubuntu setup.",
    "DOCKER_UNAVAILABLE": "Docker is not running or your user cannot access it. Start Docker and retry.",
    "HOST_CODEX_REQUIRED": "Install Codex CLI on the host before using teamcodex run.",
    "LAUNCH_SETTINGS_INVALID": "Failed to read Codex launch settings.",
    "DOCKER_BROWSER_LOGIN_UNSUPPORTED": "Docker login uses device authorization. Run teamcodex login --device-auth.",
    "INSTALL_ARGUMENT_INVALID": "Usage: ./install.sh [--reset]",
    "INSTALL_PATH_EXISTS": "A file already exists at {path}; use {launcher} directly.",
    "BOOT_USER_INVALID": "Run this installer as the account that owns TeamCodex; it uses sudo for the service definition.",
    "BOOT_COLIMA_REQUIRED": "Unattended macOS boot requires Colima. With Docker Desktop, enable its Start at login setting instead.",
    "BOOT_PLATFORM_UNSUPPORTED": "Supported platforms: Ubuntu Linux and macOS with Colima",
    "BOOT_START_FAILED": "TeamCodex boot startup failed: {message}",
}


def error_message(code: str, **parameters: str) -> str:
    return MESSAGES[code].format(**parameters)
