# Generated by scripts/generate-errors.ts; do not edit.
teamcodex_error() {
  case "$1" in
    ARGUMENT_VALUE_MISSING) printf '%s requires a value
' "${2}" >&2 ;;
    DOCKER_REQUIRED) printf 'Docker with the Compose plugin is required. See README.md for macOS and Ubuntu setup.
'  >&2 ;;
    DOCKER_UNAVAILABLE) printf 'Docker is not running or your user cannot access it. Start Docker and retry.
'  >&2 ;;
    HOST_CODEX_REQUIRED) printf 'Install Codex CLI on the host before using teamcodex run.
'  >&2 ;;
    LAUNCH_SETTINGS_INVALID) printf 'Failed to read Codex launch settings.
'  >&2 ;;
    DOCKER_BROWSER_LOGIN_UNSUPPORTED) printf 'Docker login uses device authorization. Run teamcodex login --device-auth.
'  >&2 ;;
    INSTALL_ARGUMENT_INVALID) printf 'Usage: ./install.sh [--reset]
'  >&2 ;;
    INSTALL_PATH_EXISTS) printf 'A file already exists at %s; use %s directly.
' "${2}" "${3}" >&2 ;;
    BOOT_USER_INVALID) printf 'Run this installer as the account that owns TeamCodex; it uses sudo for the service definition.
'  >&2 ;;
    BOOT_COLIMA_REQUIRED) printf 'Unattended macOS boot requires Colima. With Docker Desktop, enable its Start at login setting instead.
'  >&2 ;;
    BOOT_PLATFORM_UNSUPPORTED) printf 'Supported platforms: Ubuntu Linux and macOS with Colima
'  >&2 ;;
    BOOT_START_FAILED) printf 'TeamCodex boot startup failed: %s
' "${2}" >&2 ;;
    *) return 2 ;;
  esac
}
