import { ERROR_CODES } from '@teamcodex/core/errors';
import { readFile, writeFile } from '@teamcodex/shared/filesystem';

const check = process.argv.includes('--check');
const definitions = Object.entries(ERROR_CODES).sort((a, b) => a[1].opcode - b[1].opcode);
const quote = (value: string): string => `'${  value.replaceAll("'", "'\\''")  }'`;
let shell = '# Generated by scripts/generate-errors.ts; do not edit.\nteamcodex_error() {\n  case "$1" in\n';
for (const [code, definition] of definitions.filter(([code, value]) => value.opcode >= 9000 || code === 'ARGUMENT_VALUE_MISSING')) {
  let count = 1;
  const args: string[] = [];
  const format = definition.message.replaceAll('%', '%%').replace(/\{\w+\}/g, () => {
    args.push(`"\${${  ++count  }}"`);
    return '%s';
  });
  shell += `    ${code}) printf ${quote(`${format  }\n`)} ${args.join(' ')} >&2 ;;\n`;
}
shell += '    *) return 2 ;;\n  esac\n}\n';
const python = `# Generated by scripts/generate-errors.ts; do not edit.\nMESSAGES = {\n${
  definitions.filter(([, value]) => value.opcode >= 9000).map(([code, value]) =>
    `    ${JSON.stringify(code)}: ${JSON.stringify(value.message)},`).join('\n')
  }\n}\n\n\ndef error_message(code: str, **parameters: str) -> str:\n    return MESSAGES[code].format(**parameters)\n`;
const header = `# Error codes

Generated from [packages/core/src/errors.ts](../packages/core/src/errors.ts) by \`bun run errors:generate\`.
Edit the registry, then regenerate this table and the shell/Python message adapters.
\`bun run errors:check\` detects stale generated files.

Codes and numeric opcodes are stable application identifiers, not HTTP statuses or
CPU instructions. Never renumber or reuse them. Groups: 1000 config, 2000 OAuth,
3000 proxy, 4000 usage resets, 5000 smoke, 6000 CLI errors, 7000 diagnostics,
8000 TUI, 9000 installation/boot.

Use \`createError(code, parameters, { cause })\` for thrown errors,
\`errorMessage(code, parameters)\` for diagnostics, and \`errorResponse\` for proxy JSON.
Thrown errors expose \`code\` and \`opcode\`; proxy-generated JSON adds both fields
while retaining existing messages/types and HTTP statuses. CLI/TUI/host messages
keep their existing text. Do not expose credentials in message parameters.

Native errors retain their original codes and causes. Provider responses, retry
status codes, and persisted reset outcomes keep their existing contracts. Successful
lifecycle messages and command-help text are not error definitions. Healthcheck
failures retain the container's exit-status-only interface. Registry misuse throws
native TypeError to avoid recursively calling a broken registry.

| Opcode | Code | Message template |
| --- | --- | --- |
`;
const docs = `${header + definitions.map(([code, value]) =>
  `| ${value.opcode} | \`${code}\` | ${value.message.replaceAll('|', '\\|').replaceAll('\n', '<br>').replaceAll('<html>', '&lt;html&gt;').replaceAll('<', '&lt;')} |`).join('\n')  }\n`;
const outputs: [string, string][] = [['scripts/errors.sh', shell], ['scripts/errors.py', python], ['docs/errors.md', docs]];
for (const [path, content] of outputs) {
  if (check) {
    if (await readFile(path, 'utf8') !== content) {
      console.error(`${path} is stale; run bun run errors:generate`);
      process.exitCode = 1;
    }
  } else await writeFile(path, content);
}
